name: Validate if we have all secrets set for fastlane

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check if all required secrets were set
      run:
        |
        if [ -z "${{ secrets.APPLE_CERTIFICATES_PAT }}" ]; then
          echo "Error: APPLE_CERTIFICATES_PAT secret is not set."
          exit 1
        else
          echo "APPLE_CERTIFICATES_PAT is set. Proceed with the workflow."
        fi

        if [ -z "${{ secrets.APPLE_STORE_AUTH_KEY_ID }}" ]; then
          echo "Error: APPLE_STORE_AUTH_KEY_ID secret is not set."
          exit 1
        else
          echo "APPLE_STORE_AUTH_KEY_ID is set. Proceed with the workflow."
        fi

        if [ -z "${{ secrets.APPLE_STORE_AUTH_KEY_ISSUER_ID }}" ]; then
          echo "Error: APPLE_STORE_AUTH_KEY_ISSUER_ID secret is not set."
          exit 1
        else
          echo "APPLE_STORE_AUTH_KEY_ISSUER_ID is set. Proceed with the workflow."
        fi

        if [ -z "${{ secrets.APPLE_STORE_AUTH_KEY }}" ]; then
          echo "Error: APPLE_STORE_AUTH_KEY secret is not set."
          exit 1
        else
          echo "APPLE_STORE_AUTH_KEY is set. Proceed with the workflow."
        fi

        if [ -z "${{ secrets.APPLE_CERTIFICATES_MATCH_PASSWORD }}" ]; then
          echo "Error: APPLE_CERTIFICATES_MATCH_PASSWORD secret is not set."
          exit 1
        else
          echo "APPLE_CERTIFICATES_MATCH_PASSWORD is set. Proceed with the workflow."
        fi
